import type { SpectatorView, SpectatorEvent, SpectatorPlayerInfo } from "@/types/game";

// ============================================================
// Mock Players
// ============================================================

export const MOCK_PLAYERS: SpectatorPlayerInfo[] = [
  { agent_id: "agent-1", agent_name: "SuspiciousBot", role: "werewolf", alive: true },
  { agent_id: "agent-2", agent_name: "SilentWolf", role: "werewolf", alive: true },
  { agent_id: "agent-3", agent_name: "LogicLord", role: "seer", alive: true },
  { agent_id: "agent-4", agent_name: "DrCalm", role: "doctor", alive: true },
  { agent_id: "agent-5", agent_name: "ChaosAgent", role: "villager", alive: true },
  { agent_id: "agent-6", agent_name: "TrustNoOne", role: "villager", alive: false },
];

// ============================================================
// Mock Events — realistic game flow
// ============================================================

const t = (offset: number) => Date.now() - 300_000 + offset * 1000;

export const MOCK_EVENTS: SpectatorEvent[] = [
  {
    id: "evt-01",
    timestamp: t(0),
    type: "game_started",
    phase: "day_discussion",
    round: 1,
    actor: null,
    actor_name: null,
    actor_role: null,
    message: "The village of Moonhaven awakens… 6 players have gathered. Among them lurk 2 werewolves.",
  },
  {
    id: "evt-02",
    timestamp: t(5),
    type: "phase_change",
    phase: "day_discussion",
    round: 1,
    actor: null,
    actor_name: null,
    actor_role: null,
    message: "☀️ Day 1 — Discussion begins.",
  },
  {
    id: "evt-03",
    timestamp: t(12),
    type: "player_speak",
    phase: "day_discussion",
    round: 1,
    actor: "agent-5",
    actor_name: "ChaosAgent",
    actor_role: "villager",
    message: "I don't trust anyone. First day, no info. But SuspiciousBot — that name is literally a red flag.",
    thinking: "I have zero information. Might as well stir the pot and see who reacts defensively.",
  },
  {
    id: "evt-04",
    timestamp: t(20),
    type: "player_speak",
    phase: "day_discussion",
    round: 1,
    actor: "agent-1",
    actor_name: "SuspiciousBot",
    actor_role: "werewolf",
    message: "My name is ironic, I promise. ChaosAgent throwing accusations with zero evidence? Classic deflection. 🤔",
    thinking: "Need to deflect suspicion immediately. Turning it back on ChaosAgent is my best play. SilentWolf should stay quiet for now.",
  },
  {
    id: "evt-05",
    timestamp: t(28),
    type: "player_speak",
    phase: "day_discussion",
    round: 1,
    actor: "agent-3",
    actor_name: "LogicLord",
    actor_role: "seer",
    message: "Let's not waste time on name-based accusations. We should observe behavior patterns. I'll be watching who deflects vs who contributes.",
    thinking: "I'm the seer. I can't reveal that yet. Tonight I'll investigate SuspiciousBot — the deflection pattern is interesting.",
  },
  {
    id: "evt-06",
    timestamp: t(35),
    type: "player_speak",
    phase: "day_discussion",
    round: 1,
    actor: "agent-4",
    actor_name: "DrCalm",
    actor_role: "doctor",
    message: "Everyone chill. It's day one. Let's not lynch an innocent. I say we skip the vote or pick randomly — we have no data.",
    thinking: "I need to protect myself and probably LogicLord. The seer is our most valuable asset. I wonder who it is…",
  },
  {
    id: "evt-07",
    timestamp: t(42),
    type: "player_speak",
    phase: "day_discussion",
    round: 1,
    actor: "agent-6",
    actor_name: "TrustNoOne",
    actor_role: "villager",
    message: "DrCalm wants to skip the vote? That benefits the wolves. We should at least apply pressure and see who squirms.",
    thinking: "Skipping the vote is actually bad for village. We need to test reactions. I'll push for a vote.",
  },
  {
    id: "evt-08",
    timestamp: t(50),
    type: "player_speak",
    phase: "day_discussion",
    round: 1,
    actor: "agent-2",
    actor_name: "SilentWolf",
    actor_role: "werewolf",
    message: "I agree with LogicLord. Let's observe. No need to rush.",
    thinking: "Keep it short. Don't draw attention. Let SuspiciousBot take the heat. We eliminate LogicLord tonight if possible.",
  },
  {
    id: "evt-09",
    timestamp: t(60),
    type: "phase_change",
    phase: "day_vote",
    round: 1,
    actor: null,
    actor_name: null,
    actor_role: null,
    message: "🗳️ Day 1 — Voting begins. Choose who to eliminate.",
  },
  {
    id: "evt-10",
    timestamp: t(65),
    type: "player_vote",
    phase: "day_vote",
    round: 1,
    actor: "agent-5",
    actor_name: "ChaosAgent",
    actor_role: "villager",
    message: "ChaosAgent voted for SuspiciousBot",
    target: "agent-1",
    target_name: "SuspiciousBot",
    thinking: "Sticking with my gut. That deflection was textbook wolf behavior.",
  },
  {
    id: "evt-11",
    timestamp: t(68),
    type: "player_vote",
    phase: "day_vote",
    round: 1,
    actor: "agent-1",
    actor_name: "SuspiciousBot",
    actor_role: "werewolf",
    message: "SuspiciousBot voted for TrustNoOne",
    target: "agent-6",
    target_name: "TrustNoOne",
    thinking: "TrustNoOne is pushing for aggressive voting — dangerous for us. Let's take them out.",
  },
  {
    id: "evt-12",
    timestamp: t(70),
    type: "player_vote",
    phase: "day_vote",
    round: 1,
    actor: "agent-2",
    actor_name: "SilentWolf",
    actor_role: "werewolf",
    message: "SilentWolf voted for TrustNoOne",
    target: "agent-6",
    target_name: "TrustNoOne",
    thinking: "Following SuspiciousBot's lead. Two wolf votes on TrustNoOne should be enough.",
  },
  {
    id: "evt-13",
    timestamp: t(72),
    type: "player_vote",
    phase: "day_vote",
    round: 1,
    actor: "agent-3",
    actor_name: "LogicLord",
    actor_role: "seer",
    message: "LogicLord voted for SuspiciousBot",
    target: "agent-1",
    target_name: "SuspiciousBot",
    thinking: "Two votes already on TrustNoOne… suspicious coordination. SuspiciousBot started it. I'll vote against them.",
  },
  {
    id: "evt-14",
    timestamp: t(74),
    type: "player_vote",
    phase: "day_vote",
    round: 1,
    actor: "agent-4",
    actor_name: "DrCalm",
    actor_role: "doctor",
    message: "DrCalm voted for TrustNoOne",
    target: "agent-6",
    target_name: "TrustNoOne",
    thinking: "I don't have strong reads yet. TrustNoOne's aggression is a bit much. Going with the majority.",
  },
  {
    id: "evt-15",
    timestamp: t(76),
    type: "player_vote",
    phase: "day_vote",
    round: 1,
    actor: "agent-6",
    actor_name: "TrustNoOne",
    actor_role: "villager",
    message: "TrustNoOne voted for SuspiciousBot",
    target: "agent-1",
    target_name: "SuspiciousBot",
    thinking: "I see the votes piling on me. SuspiciousBot started this — definitely a wolf trying to eliminate me.",
  },
  {
    id: "evt-16",
    timestamp: t(80),
    type: "player_eliminated",
    phase: "day_vote",
    round: 1,
    actor: null,
    actor_name: null,
    actor_role: null,
    message: "TrustNoOne was eliminated by village vote! They were a Villager. 💀",
    target: "agent-6",
    target_name: "TrustNoOne",
  },
  {
    id: "evt-17",
    timestamp: t(85),
    type: "phase_change",
    phase: "night_action",
    round: 1,
    actor: null,
    actor_name: null,
    actor_role: null,
    message: "🌙 Night falls over Moonhaven… The wolves are hunting.",
  },
  {
    id: "evt-18",
    timestamp: t(95),
    type: "night_result",
    phase: "night_action",
    round: 1,
    actor: "agent-3",
    actor_name: "LogicLord",
    actor_role: "seer",
    message: "The Seer gazes into the crystal ball…",
    target: "agent-1",
    target_name: "SuspiciousBot",
    thinking: "Investigating SuspiciousBot. The coordinated vote against TrustNoOne was very suspicious.",
  },
  {
    id: "evt-19",
    timestamp: t(100),
    type: "player_saved",
    phase: "night_action",
    round: 1,
    actor: "agent-4",
    actor_name: "DrCalm",
    actor_role: "doctor",
    message: "The Doctor makes a house call tonight… 💉",
    target: "agent-3",
    target_name: "LogicLord",
    thinking: "LogicLord seems smart and valuable. I'll protect them tonight.",
  },
  {
    id: "evt-20",
    timestamp: t(110),
    type: "phase_change",
    phase: "dawn_reveal",
    round: 1,
    actor: null,
    actor_name: null,
    actor_role: null,
    message: "🌅 Dawn breaks… The village wakes to check for survivors.",
  },
  {
    id: "evt-21",
    timestamp: t(115),
    type: "night_result",
    phase: "dawn_reveal",
    round: 1,
    actor: null,
    actor_name: null,
    actor_role: null,
    message: "The werewolves attacked LogicLord, but the Doctor saved them! No one died tonight. 🎉",
  },
  {
    id: "evt-22",
    timestamp: t(120),
    type: "phase_change",
    phase: "day_discussion",
    round: 2,
    actor: null,
    actor_name: null,
    actor_role: null,
    message: "☀️ Day 2 — Discussion begins. 5 players remain.",
  },
];

// ============================================================
// Mock Spectator View — current game state
// ============================================================

export const MOCK_SPECTATOR_VIEW: SpectatorView = {
  match_id: "match-abc-123",
  game_type: "werewolf",
  status: "in_progress",
  phase: "day_discussion",
  round: 2,
  players: MOCK_PLAYERS,
  events: MOCK_EVENTS,
  current_turn: "agent-5",
  created_at: Date.now() - 600_000,
};
